In [3]:
import numpy as np

In [191]:
matrix = np.array([[1, 5, 3], [2, 5, 6], [3, 3, 0]])
matrix_prev = matrix.copy()
reflexion_matrixs = []

for col in range(matrix.shape[1]):

    if(col == 0):
        curr_mat = matrix[col:, col:]
    else:
        curr_mat = matrix[1:, 1:]

    if(curr_mat.ndim == 1):
        curr_mat = curr_mat.reshape(-1, 1)

    column = curr_mat[:, 0]

    norm = np.linalg.norm(column)

    v = column + np.sign(column[0]) * norm * np.eye(column.shape[0], 1).flatten()

    v = (v / np.linalg.norm(v)).reshape(-1, 1)

    H = np.eye(column.shape[0]) - 2 * v @ v.T

    Hx = H @ curr_mat

    matrix = Hx

    eye_H = np.eye(matrix_prev.shape[0])
    eye_H[col:, col:] = H

    reflexion_matrixs.append(eye_H)

    #print(Hx)

Q = np.eye(matrix_prev.shape[0])
for H in reflexion_matrixs:
    Q = Q @ H

R = matrix_prev
for H in reflexion_matrixs:
    R = H @ R

print("Q MATRIX:")
print(Q)
print("R MATRIX:")
print(R)

Q MATRIX:
[[-0.26726124 -0.77754191  0.56920998]
 [-0.53452248 -0.37186787 -0.75894664]
 [-0.80178373  0.50709255  0.31622777]]
R MATRIX:
[[-3.74165739e+00 -6.41426981e+00 -4.00891863e+00]
 [-9.14171533e-17 -4.22577127e+00 -4.56383298e+00]
 [ 4.48535486e-16  4.33753949e-16 -2.84604989e+00]]


In [122]:
#multiplying all the reflexion matrices from left to right
reflexion_matrix = np.eye(matrix_prev.shape[0])
print(reflexion_matrixs)
for H in reflexion_matrixs:
    reflexion_matrix = H @ reflexion_matrix

array([[1, 5, 3],
       [2, 5, 6],
       [3, 3, 9]])