In [1]:
import numpy as np

In [33]:

matrix = np.array([[1, 5, 3], [2, 5, 6], [3, 3, 0]])
matrix_prev = matrix.copy()

G_arr = []

# Iterace přes sloupce
for i in range(min(matrix.shape[0], matrix.shape[1])):  # Zajišťuje, že nepřekročíme dimenze
    # Iterace přes řádky pod hlavní diagonálou
    for j in range(i+1, matrix.shape[0]):
        givens_matrix = np.eye(matrix.shape[0])

        # Výpočet koeficientů rotace
        cos = matrix[i, i] / np.sqrt(matrix[i, i]**2 + matrix[j, i]**2)
        sin = matrix[j, i] / np.sqrt(matrix[i, i]**2 + matrix[j, i]**2)

        # Nastavení prvků matice rotace
        givens_matrix[i, i] = cos
        givens_matrix[j, j] = cos
        givens_matrix[j, i] = -sin
        givens_matrix[i, j] = sin

        # Aplikace rotace na matici
        matrix = givens_matrix @ matrix

        # Ukládání rotací pro pozdější výpočet Q
        G_arr.append(givens_matrix)

R = matrix  # Výsledná horní trojúhelníková matice R

# Výpočet Q jako produktu transponovaných matic Givensových rotací
Q = np.eye(matrix.shape[0])
for g in G_arr:
    Q = Q @ g.T

# Výpis výsledků
print("Q MATRIX:")
print(Q)
print("R MATRIX:")
print(R)


Q MATRIX:
[[ 0.26726124  0.77754191 -0.56920998]
 [ 0.53452248  0.37186787  0.75894664]
 [ 0.80178373 -0.50709255 -0.31622777]]
R MATRIX:
[[ 3.74165739e+00  6.41426981e+00  4.00891863e+00]
 [ 0.00000000e+00  4.22577127e+00  4.56383298e+00]
 [ 0.00000000e+00 -3.87495173e-16  2.84604989e+00]]


In [36]:
# Eigen values


array([[ 1.        ,  2.90929545, -2.12978872],
       [ 3.97305547,  6.5587922 , -0.44393148],
       [ 5.7928164 ,  3.37103442,  0.28178921]])